### ISSUE TITLE
can't compile mac or ios

### ISSUE THREAD

**Issue by olilarkin** [olliwang/moui-nanovg-example#1]
this looks very interesting, but won't compile for me. freetype wouldn't clone, so i put the 2.4.2 source there manually

Ld build/Debug/MouiDemo.app/Contents/MacOS/MouiDemo normal x86_64
    cd "/Users/oli/Dev/GUI Framework Tests/moui-nanovg-example/mac"
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/Debug -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks -F/Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/Debug -filelist /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/demo.build/Debug/MouiDemo-Mac.build/Objects-normal/x86_64/MouiDemo.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/demo.build/Debug/MouiDemo-Mac.build/Objects-normal/x86_64/MouiDemo_lto.o -fobjc-arc -fobjc-link-runtime /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/app/build/Debug/libapp.a /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/deps/moui/moui/build/Debug/libmoui.a /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/deps/moui/moui/build/Debug/libnanovg.a /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/deps/moui/moui/build/Debug/libfreetype.a -framework Cocoa -framework CoreVideo -framework Metal -framework QuartzCore -Xlinker -dependency_info -Xlinker /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/demo.build/Debug/MouiDemo-Mac.build/Objects-normal/x86_64/MouiDemo_dependency_info.dat -o /Users/oli/Dev/GUI\ Framework\ Tests/moui-nanovg-example/mac/build/Debug/MouiDemo.app/Contents/MacOS/MouiDemo

Undefined symbols for architecture x86_64:
  "_FT_Stream_OpenGzip", referenced from:
      _PCF_Face_Init in libfreetype.a(pcf.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by olliwang** [comment]
`freetype` is a submodule of `moui`. Make sure you update all submodule recursively and run the `gyp` command again. `moui` already filters out files that may cause compilation errors at https://github.com/ollix/moui/blob/master/moui/freetype.gyp

**Comment by olilarkin** [comment]
thanks. ft git was down yesterday. today it works
