### ISSUE TITLE
Paths not drawing correctly in NVGMetal - antialiasing wrong?

### ISSUE THREAD

**Issue by olilarkin** [olliwang/moui-nanovg-example#2]
Since a recent change in MetalNanoVG the nanovg demo is not drawing correctly on my mac*. It looks like there might be an issue with antialiasing. Here is the demo in opengl vs metal modes:

![screen shot 2019-02-07 at 10 13 01](https://user-images.githubusercontent.com/655662/52404506-16bc3a80-2ac1-11e9-8194-a5671c2669ca.png)
![screen shot 2019-02-07 at 10 12 33](https://user-images.githubusercontent.com/655662/52404507-16bc3a80-2ac1-11e9-9ce5-96f873d52010.png)

*MacBook Pro (Retina, 15-inch, Mid 2014) | NVIDIA GeForce GT 750M 2048 MB | Intel Iris Pro 1536 MB

**Comment by olliwang** [comment]
Weird, the latest update was merely trying to fix the unwanted effect while resizing the window. It doesn't touch the code of MetalNanoVG except moving the setting drawable size part to moui. Did you update all submodules? The demo looks normal on my iMac (Retina 5K, 27-inch, Late 2014).
<img width="1112" alt="screen shot 2019-02-07 at 18 18 10" src="https://user-images.githubusercontent.com/76374/52404939-2c535380-2b05-11e9-8c55-5286360096c7.png">

**Comment by olilarkin** [comment]
this was happening prior to the latest update, i think it is when you switched to ARC... but that is a guess

**Comment by olliwang** [comment]
Can you try deleting the `mac/build` folder and regenerating a new Xcode project to see if the issue still there?

**Comment by olliwang** [comment]
My bad, just found out that I forgot to enable antialias for moui's widget view. Just fixed. https://github.com/olliwang/moui-nanovg-example/commit/bb677e1526c9f8b8a6105f4d64d8885ee03bfea4

**Comment by olilarkin** [comment]
thanks, fixed... got another issue with context size on non-retina screen. will make a separate issue
