### ISSUE TITLE
context wrong size when switching between retina/non retina screen

### ISSUE THREAD

**Issue by olilarkin** [olliwang/moui-nanovg-example#3]
If i build with METAL nanovg on a non retina screen the metal context is 1/2 the size it should be.

![screen shot 2019-02-07 at 10 49 03](https://user-images.githubusercontent.com/655662/52406629-12dee700-2ac6-11e9-9dd3-71ff2d9f4242.png)

If I build with OpenGL it is correct, until i drag the window to retina screen, when it is the wrong size

**Comment by olliwang** [comment]
Thanks. I forgot to consider non-Retina screens in a recent update. Just fixed.  https://github.com/olliwang/moui-nanovg-example/commit/b6231cd60a0411c893852205ea545656fc8d9c86

**Comment by olilarkin** [comment]
METAL drawable size is now correct when launching on non-retina screen. Maybe you know but, if you drag the window from non-retina to retina, it doesn't update the backing resolution. Likewise if you drag with openGL from non-retina to retina the context dimensions are wrong. Those things probably deserve a separate issue, so closing this
