### ISSUE TITLE
Is there some example on how to use the widget Button

### ISSUE THREAD

**Issue by faywong** [olliwang/moui-nanovg-example#4]
I have tried this, but it doesn't work as expected.

```c++
  auto button = new moui::Button();
  button->SetWidth(100.0f);
  button->SetHeight(100.0f);
  button->SetHighlighted(true);
  button->SetTitle("sid hello", moui::ControlState::kSelected);
  widget_view_->root_widget()->set_background_color(nvgRGBf(0, 0, 0));
  widget_view_->root_widget()->set_is_opaque(true);
  widget_view_->root_widget()->AddChild(button);

```

The actual effect is:
![image](https://user-images.githubusercontent.com/1934627/70905227-50919200-203e-11ea-810f-bff118ef9267.png)

**Comment by olliwang** [comment]
You set the title for `selected` state but your button is in `normal` state, which is the default button state. Try changing `moui::ControlState::kSelected` to `moui::ControlState::kNormal` or adding `button->SetSelected(true)`.

**Comment by faywong** [comment]
I see that the demo.c has absolutely not used the wigets, are these widgets work out of box?

**Comment by olliwang** [comment]
Yes. But keep in mind that `moui` is no longer actively maintained. We have a new close sourced project to replace this project. If you still want to use `moui`, you will need to figure out how it works by yourself.

**Comment by faywong** [comment]
OK. Many thanks for clarify and your great work on moui. I am working on combining glfm + nanogui for my cross platform gui kit.
